### ISSUE TITLE
Deploy/manage/update configuration using OOTB ML packaging

### ISSUE THREAD

**Issue by peterskim12** [marklogic/roxy#111]
Currently, we're relying on an unpublished/for-internal-use-only REST endpoint to execute adhoc XQuery code for managing server configuration. Engineering may change this at any time and have no obligation to take external use into consideration (currently facing issues with this and changes in ML7).

One way of doing this in a more kosher manner may be to use the OOTB configuration manager/packaging functionality. This would also help reduce the amount of XQuery code in the Roxy Deployer.

**Comment by grtjn** [comment]
This ticket is outdated.

We have moved to using :8000/v1/eval for MarkLogic 8+, and only use the old approach for ML7- but anticipate that will get removed once ML7 has been EOL'ed (end of 2017).

Packaging api has not progressed since ML6, and all focus has been rerouted to the Management REST api as of ML8. The latter would be the preferred choice when we migrate to a different bootstrap strategy.
