### ISSUE TITLE
Allow capturing modules for any app-type

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#223]
You sometimes want to capture an existing Roxy app from a production server, for example to check whether what you locally have is identical. This requires capturing the modules of any type.

**Comment by alencruz** [comment]
I have added the ability to capture modules for any application type to ML7 and taken the protection off which will allow to capture modules for any application type in ML5,6, and 7. For ML7 if it’s a REST application, REST will still be used to capture since it’s faster and more comprehensive than the query based method. Pull request to follow.

**Comment by grtjn** [comment]
Fixed in dev
