### ISSUE TITLE
self-test is failing

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#339]
Error:

    <error:message>Depending tasks on host or group.</error:message>
    <error:format-string>ADMIN-DEPENDINGSCHEDULEDTASKS: (err:FOER0000) There are depend tasks on the host or the associated group. Delete those first before moving host 15806429371048342259 to a new group.</error:format-string>

Seems to be related to the tests involving groups.

**Comment by grtjn** [comment]
You should self-test against a clean environment. If you test against your local box, and you have some schedules from whichever project running, then it fails..


Sent from Samsung Mobile

**Comment by grtjn** [comment]
I couldn't think of a workaround back then, still can't really think of one now. I think it is because there could be scheduled tasks in the Default group, and if you move all hosts to a different group, that will cause schedules of Default group to stop running. I can only suggest doing a self-test against an empty environment from now on.. :-S

**Comment by grtjn** [comment]
I was thinking of improving self-test to a) wipe better at failure, and b) detect cluster and skip group stuff if not found..

**Comment by dmcassel** [comment]
I think your original idea of just testing against a clean box makes sense. If tests pass that way, I'm fine with closing this one.

**Comment by paxtonhare** [comment]
it tests on a clean box. closing
