### ISSUE TITLE
Corb doesn't run against ML8

### ISSUE THREAD

**Issue by grtjn** [marklogic/roxy#391]
I suspect the XCC 5 jar is a bit too old to run properly against ML8. Seems to work against ML7..

**Comment by dmcassel** [comment]
ML5 is due to be end-of-life'd in May, so if there's a jar that works for ML 6-8, we could go with that one.

**Comment by paxtonhare** [comment]
I'm thinking we might want to yank the jar. Let the user provide their own.

**Comment by dmcassel** [comment]
Seems reasonable to me. If Roxy can't find a jar, it would be useful to have a message saying "To use corb, you must download XCC and set the *whatever* property to the location of the XCC jar file" -- rather than just "jar not found".

**Comment by paxtonhare** [comment]
Agreed

**Comment by grtjn** [comment]
You could then argue that the user could provide entire Corb, like it is now expected to provide MLCP itself. Add `corb-home` and perhaps `corb-vmargs`. Searching jars would then be done against corb-home, instead of the internal jars location..

**Comment by kefo** [comment]
At the risk of asking a naive question, why remove the jar - and corb - altogether instead of exploring the possibility of updating the jars?

I ask because when roxy ships with these types of helper libraries, everything 'just works' and that is a nice experience (especially when you look at `./ml --help` and see corb there).

I'm happy to test corb using the XCC version for ML7 against ML7.  I could look into testing XCC version 7 against ML6 and ML8 also, but not as easily.  Would that help sway this discussion?

**Comment by dmcassel** [comment]
The current challenge is that the "just works" part stopped being true with ML8. If there's an XCC lib that works with ML6, 7, and 8, then I think it is nice to include the jar.

**Comment by paxtonhare** [comment]
We could look in to magically downloading the right jar depending your ml
version.

Another reason to ditch the file is to reduce download size.

Conversely, I know of a few cases where orgs have to sign off on all
software installed. Getting corb as part of the install is one less
approval step for them to go through. @sparnell, do you have any input on
that?

**Comment by grtjn** [comment]
Easier fix, looks like Corb runs just fine with marklogic-xcc-8.0-1.jar against latest ML5. I'll trade out that jar..

**Comment by grtjn** [comment]
By the way, anyone got a clue which version of Corb we are shipping? (And for that matter, how about the other jars?)

**Comment by paxtonhare** [comment]
fixed in dev
