### ISSUE TITLE
Default settings for database configuration 

### ISSUE THREAD

**Issue by miguelrgonzalez** [marklogic/roxy#43]
It will be quite handy that during setup:apply-database-settings at xquery/setup.xqy, instead of doing nothing whenever a value it's not set, it would default to some other value.

Like this, we would make sure that the database configuration and the configuration are perfectly aligned after a bootstrap.

Example: 

``` xquery
let $value := setup:get-setting-from-database-config-as-string($database-config, "directory-creation")
let $admin-config :=
   if ($value) then
       admin:database-set-directory-creation($admin-config, $database, $value)
  else
       admin:database-set-directory-creation($admin-config, $database, "manual")
```

After a bootstrap it won't matter if somebody changed the setting manually or somebody removed the line from the config file. The setting will default to Manual and automatic directory creation will be disabled.

Thanks!

Again: I could send a pull request if you think it's interesting for everybody else.

**Comment by grtjn** [comment]
Old ticket, but still thinking the same. The current implementation was by design, and it would touch a lot of code to change this. Moreover, it would hard-code particular defaults where you most often don't want to. Think about cache settings for instance.

If you like to make all database options explicit, consider copying in this config fragment with settings from an out of the box Documents database: https://github.com/marklogic/roxy/blob/master/deploy/sample/default-docs-config.sample.xml
