### ISSUE TITLE
undefined local variable or method `transformname'

### ISSUE THREAD

**Issue by Thijxx** [marklogic/roxy#506]
This error occurs when following the exact steps here: https://docs.marklogic.com/guide/rest-dev/transforms#id_26300

Seems to me there is something missing in the ML documentation about naming the transformation or Roxy does not deploy the tranform in sjs right?

**Comment by dmcassel** [comment]
I just tried this and got a similar result. It's not actually a bug; rather, it's a difference in how the name of the transform is determined. In the example you linked to, the file is called "trans-ex.sjs", but it is deployed to http://localhost:8000/LATEST/config/transforms/js-example. The name js-example is not in the code, so Roxy has no way of coming up with that name. Instead, Roxy uses the file name. 

My steps:

- created a Roxy project with --app-type=rest
- copied the provided code to rest-api/transforms/trans-ex.sjs
- bootstrapped, deployed modules
- verified that the transform was deployed at http://localhost:8050/v1/config/transforms
  - Note that the documentation example is working with port 8000. If you check there, you won't see it, because that's a different modules database. 
  - the transform was successfully deployed with the name "trans-ex", derived from the filename. 
- Attempted the document insert shown in the documentation example. It failed, as expected: "RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: Extension js-example does not exist."
- Retried the document insert example, using "trans-ex" for the transformation name and 8050 as the port. It worked. 

@Thijxx, please confirm that this addresses what you saw.

**Comment by Thijxx** [comment]
I do not understand what you did but these are my steps. You 'verify that the transform was deployed' at step 4 but that is exactly my issue, thats not posible. 

***cswifi-transform.sjs***

```
/* =======================================================================  
   ! Information                                                           
   ======================================================================= 
   
   API Extension: Transformation voor CS Wifi data
   File:          cswifi-transform.sjs
   Version:       0.1
   Date:          2015-08-17
   Authors:       Thijs van Ulden
   Copyright:     DIKW
  
   =======================================================================  
*/

function cswifi-transform(context, params, content) 
{
    
};

exports.transform = cswifi-transform;
```

Then I deploy this with:
```./ml local deploy transform --file=cswifi-transform.sjs```

And then I get this error:
```
ERROR: undefined local variable or method `transformname' for #<ServerConfig:0x0000000064f410>
ERROR: ["/home/thijs/Repos/rws-vriend/vriend/deploy/lib/server_config.rb:1568:in `deploy_transform'", "/home/thijs/Repos/rws-vriend/vriend/deploy/lib/server_config.rb:842:in `deploy'", "deploy/lib/ml.rb:155:in `<main>'"]
```

**Comment by grtjn** [comment]
I'm afraid that is a plain bug. It looks like the command used to take a transformname as param, but now takes --file instead. Code still refers to transformname though. It needs to be derived from the filename.

I think you can bypass this issue by not using the --file flag, which I think would cause all transforms to get loaded..

**Comment by Thijxx** [comment]
Yes that is a useful work-around. Thanks.

**Comment by grtjn** [comment]
Fixed in dev..
