### ISSUE TITLE
Override build_config is not possible because of global substitution at the end of the function

### ISSUE THREAD

**Issue by peetkes** [marklogic/roxy#510]
I wanted to override the build_config function to add in an extra database and test database for unittesting but the global properties substitution at the end of the build_config will remove all my special substitutions in the config file.

This could be resolved by creating a wrapper that resolves the global substitutions after the build-config has been executed.

Remove this from build_config
```ruby
      @properties.sort {|x,y| y <=> x}.each do |k, v|
        config.gsub!("@#{k}", v)
      end
```
and add this function to resolve this.
```ruby
  def build_config_wrapper(config_file)
      config = build_config(config_file)
      @properties.sort {|x,y| y <=> x}.each do |k, v|
        config.gsub!("@#{k}", v)
      end
      config
  end
```

**Comment by grtjn** [comment]
Should be minor change, but pushing away nonetheless..

**Comment by RobertSzkutak** [comment]
It looks like the build_config code has been refactored quite a bit since this issue was opened. I'm trying to put together a test case to see if this is still valid.

Would doing something like this to app_specific.rb and then checking if the change persists cover it? (I'm still playing with the code and just trying to get the idea of the test here):

`alias_method :original_build_config, :build_config

  # then you would define your new method
  def build_config(config_files)
    configs = []
    config_files.split(",").each do |config_file|
      config = File.read(config_file)
      config = original_build_config(config_file)
      config.gsub!("@ml.test-modules-db-xml", test_modules_db_xml) ##To replace with something else...
      config.gsub!("@ml.test-modules-db-assignment", test_modules_db_assignment) ##To replace with something else...
      configs << config
    end
    %Q{(#{configs.join(", ")})}
   end`

Thanks in advance!

**Comment by RobertSzkutak** [comment]
Thinking about this more... Wouldn't the simplest way to add an extra DB be to just be to edit ml-config? What's the value of substituting config information this way instead of just changing ml-config? Alternatively, couldn't one also argue that it could be possible to make this work by overriding the build_config function without calling the original? (Granted, that may result in a large copypaste) 

CC @dmcassel and @grtjn for opinions..

**Comment by dmcassel** [comment]
To set up test content or modules database, all you need to do is modify build.properties:

- test-content-db=${app-name}-content-test
- test-modules-db=${app-name}-modules-test

These properties are normally in present in build.properties, but commented out. (`test-modules-db` defaults to "${app-name}-modules", without the "-test".) 

If you want to add some other database, then yes, the way to do that is to copy put it into ml-config, specifying settings and referring to properties as needed. 

@peetkes can you say more about what you're trying to do, and whether those approaches are insufficient?

**Comment by rlouapre** [comment]
Recently I had the need to add a new app server for the unit tests. Overriding ```test_appserver``` was the solution.
Can't you do the same to add another test database by overdding ```test_content_db_xml```?
It might not be well documented...

**Comment by RobertSzkutak** [comment]
@rlouapre Roxy supports that out of the box as well. Look at the `test-port` option. When you set that it makes an additional appserver for you and it sets the modules DB and content DB to either the test DB's you defined or the default DB's if either of the test DB's are not defined.

Was this insufficient for you?

**Comment by rlouapre** [comment]
I am aware test app server will only be created when ```test-port``` and ```test-content-db``` are defined but it will only create a single http app server. 
In my scenario I needed a second app server for testing.

**Comment by dmcassel** [comment]
@rlouapre regarding test_appserver, you did that in app_specific.rb, right? If you did it in server_config.rb, it will get overwritten the next time you upgrade Roxy. 

I'm curious about the use case for having two app servers for testing. Can you expand on that?

**Comment by RobertSzkutak** [comment]
@dmcassel I've seen at least one case out in the field where a client wanted an HTTP and an HTTPS test appserver. I've also seen a case where the client wanted one server with LDAP and one with internal auth. Perhaps not whats going on here, but worth noting. For these cases though, we just edited ml-config appropriately.

**Comment by rlouapre** [comment]
We have 2 test app servers: one using interpretive rewriter and one using declarative rewriter.

**Comment by dmcassel** [comment]
Closing because:

- the original issue is over a year old
- it's unclear whether the original issue is still a problem
- more recently, we've discussed creating extra unit test databases and app servers, but there are ways to do that

@rlouapre @peetkes if you still see an issue here, please open a new one so we can address the specific need
