### ISSUE TITLE
Username/Password not found issue with corb

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic/roxy#538]
Saw this with a client. If you have roxy setup to prompt the user for a username/password rather than have one in your *.properties file corb will give an error that there is no default username and password available to it.

I'll try to set aside some time and see if I can get a fix in the not too distant future.

**Comment by grtjn** [comment]
Having a prompt_password in there makes a lot of sense. Keep in mind prompt_password stores the value in `@ml_password`. You can also make it prompt for the user if I am not mistaken..

**Comment by jmeekhof** [comment]
I'm seeing a very similar issue. In my case I'm using `mlcp`.

In our environment, we use `app_specific.rb` to inject username and passwords from the environment variables. This method of setting username and password is working for all the normal deployment commands.

The actual issue I'm seeing, is the `-option_file` replacement is not occurring for the `@options` that are set in the `app_specific.rb`.

**Comment by grtjn** [comment]
@jmeekhof, can you show what you are using inside the options file contents? Something like `${app-name}` gets replaced properly at my end. `@ml.app-name` should work too. Maybe you forgot the ml. prefix that is necessary with the `@` notation?

FYI: `-option_file` is a typo, and should have been `-options_file`. I prepared a fix for Roxy to change that.

**Comment by jmeekhof** [comment]
Ok, I have a clearer picture now.

When I was attempting the first time, I had been using tho `@ml.user` syntax as a command line parameter. Now that I've looked at the code, I see why that didn't work. I've now put my information into a file, and the command seems to be work (I also changed the code to look for the `-options_file` parameter instead of `-option_file`).

One clarifying point is the `./ml {env} mlcp` command only can find the options file in the deploy directory. Shouldn't we allow the option file to live anywhere?

**Comment by grtjn** [comment]
The path can be relative, so you could go up with ..

I think i have a pr open that makes the roxy look from project root instead..

**Comment by RobertSzkutak** [comment]
Pushed in a fix to my open pull request: https://github.com/marklogic/roxy/pull/567

**Comment by RobertSzkutak** [comment]
Closing as my PR to fix this was accepted
