### ISSUE TITLE
Adding a new test suite requires the setup/teardown/suite-setup/suite-teardown.xqy files to be present

### ISSUE THREAD

**Issue by rhdunn** [marklogic/roxy#572]
## Overview

Running a test suite fails if the setup/teardown/suite-setup/suite-teardown.xqy files are missing.

## Use Case

As a developer, I want to easily create a new test suite to be run within the Roxy test framework.

As a developer, I want to easily see whether a test suite has any setup/teardown logic.

## System

Roxy Version: 1.6
Operating System: Windows
Web Browser: Firefox

**Comment by dmcassel** [comment]
I marked this as an enhancement, because I think @rhdunn is asking for test scaffolding.

**Comment by dmcassel** [comment]
With the current code on the dev branch, you can create a new test suite with no setup or teardown files and it works fine. I believe this has been addressed by other bug fixes. If someone can demonstrate otherwise, please re-open. Test steps:

- create `src/test/suites/my-test/`
- create `src/test/suites/my-test/test1.xqy`

test1.xqy consists of:

    xquery version "1.0-ml";
    import module namespace test="http://marklogic.com/roxy/test-helper" at "/test/test-helper.xqy";
    test:assert-true(fn:true())

Deploy & run the test suite. It executes correctly. (Likewise, it properly fails if the test is set up to fail.)
