### ISSUE TITLE
Assigning Task Host in Scheduled task

### ISSUE THREAD

**Issue by gjwilson21** [marklogic/roxy#608]
I am trying to assign a task host to a scheduled task to the ml-config.xml file. is there a provision in Roxy to specify which server, a scheduled task should run on? I couldn't find any reference to this in the documentation.

However, I just went ahead and I tried both assigning the hostname as a value to the element task-host like below, as well as passing the hostname in the name attribute, but neither worked.

       ` <scheduled-task>
            <task-path>somescript.xqy</task-path>
            <task-root>/</task-root>
            <task-type>hourly</task-type>
            <task-period>12</task-period>
            <task-minute>40</task-minute>
            <task-database name="@ml.content-db"/>
            <task-modules name="@ml.app-modules-db"/>
            <task-user name="@ml.app-name-user"/>
            <task-host>@ml.batch-search-hostname</task-host>
          </scheduled-task>`

Please advice.

Thanks
Joel

**Comment by gjwilson21** [comment]
Looks like this is fixed in the latest version of Roxy. Upgrading ROXY helped fix the issue.

**Comment by grtjn** [comment]
I think you do need to put the host name in a host attribute in latest slush, otherwise it will not attach the schedule on a single host, which means it effectively runs on all hosts within that group, in parallel..

https://github.com/marklogic/roxy/blob/0cd9666ae7e18de47da802c5bed02e077143891b/deploy/lib/xquery/setup.xqy#L4017
