### ISSUE TITLE
Bootstrap will not always update resources

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic/roxy#690]
See: https://github.com/marklogic/roxy/issues/690#issuecomment-261081647

**Comment by kford-oconnors** [comment]
The amp bug has been fixed (#614).

Regarding URI privileges, our issue has been the conflict discussed in #261, where changing the action associated with a privilege will cause bootstrap to terminate rather than replacing the privilege.

The other resource we have experienced this problem with is mimetypes. Bootstrap will not add an extension to an existing mimetype.

**Comment by dmcassel** [comment]
Filed #710 to address mimetypes and #711 for URI privileges, so that we can track the individual issues. Please add any info there that would be helpful for fixing. If there are other problematic resources, please file individual issues for them.
