### ISSUE TITLE
 ML-9 Bootstrap Error: Invalid coercion: on external-security at ml.rb line 170

### ISSUE THREAD

**Issue by dmccreary** [marklogic/roxy#706]
I am getting errors when I use Roxy to do bootstraps on ML-9.  I am using the DEV branch.

When I make some changes in the ml.config file and then re-run "ml local bootstrap" I get the following errors:

$ ml local bootstrap
Bootstrapping your project into MarkLogic 9 on localhost...
ERROR: XDMP-AS: (err:XPTY0004) $val as node()? -- Invalid coercion: (<external-security xmlns="http://marklogic.com/xdmp/group" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">...</external-security>, <external-security xmlns="http://marklogic.com/xdmp/group" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">...</external-security>) as node()?
See MarkLogic Server error log for more details.
ERROR: ... Bootstrap FAILED
ERROR: exit
ERROR: ["deploy/lib/ml.rb:170:in `exit'", "deploy/lib/ml.rb:170:in `<main>'"]

After this error occurs ALL of my roxy bootstrap projects will stop working, even on unrelated databases.

The only fix is to do a **ml local wipe**, reboot the server and reload all the content.

I have worked with Rob Szkutak on this and he has confirmed that there are no problems with the ml.config file.

A sample of one my ml.config files is here: 

https://github.com/dmccreary/marklogic-business-glossary/blob/master/deploy/ml-config.xml

Thanks! - Dan

**Comment by RobertSzkutak** [comment]
Adding to this, Dan and I have chatted back and forth a bit about this. He hasn't figured out how to reproduce this yet. But it seems that bootstraps "randomly" stop working for him for all projects on ML9. Could be indicative of a larger issue but I'm not sure.

Dan, could you also share your error log here? I remember we saw that it looked like bootstrap was failing on setting up external security which was odd because your ml-config.xml didn't use external security..

**Comment by RobertSzkutak** [comment]
I believe this was solved. Re-open if not.

**Comment by grtjn** [comment]
I wouldn't be surprised if it just was some instability with ML9 EA, or maybe even ML9 nightly. I have seen some quirks too, but thought I logged all..

**Comment by grtjn** [comment]
I could also imagine something like this happening after upgrading ML9 EA (which is officially not supported)
