### ISSUE TITLE
Remove support for RecordLoader and XQSync

### ISSUE THREAD

**Issue by dmcassel** [marklogic/roxy#724]
RecordLoader and XQSync's functionality are now handled by MLCP, which is the preferred tool to use. Dropping them would allow us to delete these files from deploy/lib/java:

- recordloader.jar
- xpp3-1.1.4c.jar
- xqsync.jar
- xstream-1.4.2.jar

Removing support would eliminate the need to upgrade these jars (#722).

**Comment by dmcassel** [comment]
Please comment on this issue if you support removing those tools, or if doing so would have a negative impact on you.

**Comment by RobertSzkutak** [comment]
XQSync should be deprecated. The official recommendation is to go with MLCP if you're running ML6 or greater. If you're using an earlier version, XQSync is still your best option. However, Roxy doesn't presently support ML6 or earlier.

There are still a couple valid use cases for RecordLoader not fulfilled by MLCP. I am aware of quite a few people who use it. That said, even MLCP usage via Roxy is low out in the field so I cant imagine too many people are using RecordLoader with MLCP.

**Comment by dmcassel** [comment]
@RobertSzkutak do you know whether there are RFEs for the RecordLoader cases not yet supported by MLCP? If there aren't could you make sure that happens (and that Justin knows about them)?

**Comment by RobertSzkutak** [comment]
Yes, I've opened RFE's. Engineering (and Justin specifically) is aware.

**Comment by heelix** [comment]
We used record loader today with roxy - adding multiple collections as part
of the ingest/jenkins process.  Please don't break this.

**Comment by RobertSzkutak** [comment]
@heelix This issue was opened in response to this one: #722 

One thing we're considering is not shipping JARs with Roxy but leaving the feature in tact (like we do with MLCP). In the future, we may also add a mechanism with which to download and install the JARs for you.

How would you feel about that? Thanks for the feedback!

**Comment by heelix** [comment]
With stock MLCP eating up 30MB of disk, the JAR size for record loader is
trivial. File size is so not an issue. (I'd go as far as saying the Roxy
distribution should include the JRoxy JAR'ed version as part of a normal
ROXY distribution too).  I'd view removal of the JAR to save on file size
foolish.

RecordLoader does a few jobs really well and is getting used at one of your
larger customers - they are also using MLCP too - so it is not like they
are unaware of the other options.  Hate to remove that because some
marketing guy thinks a core solution is better than what happened in the
field.  Heck, were that the case we would not be using Roxy!

I was not aware that xqsync can be called via ROXY.  I've only seen that
used in batch scripts.

**Comment by dmcassel** [comment]
The motivation for removal was actually that the JARs are out of date; one had triggered a security warning (#722); if no one's using the feature, then it's not worth figuring out the right JAR versions and retesting. Since we now know the feature is being used, we can say it's worthwhile to do that testing.
